version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "19999:80" 
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
